lane_detection:
    ros__parameters:
        display:                              false
        frame_id:
            lane_parameters:                  'laneParametersFrameId'
        lane_color:                           [50,234,157]
        m_per_pix:
            x:                                0.010278 # 3.7 meters / 360 pixels
            y:                                0.010417 # 5 meters / 480 pixels
        qos_length:                           10
        roi:
            height:                           151
            width1:                           151
            width2:                           405
            x1_offset:                        282
            x2_offset:                        156
            y_offset:                         329
        search_params:
            margin:                           50
            mean_limit:                       [4.5,8.5]
            min_pixels:                       40
            n_windows:                        10
        topic:
            lane_parameters:                  'lane/parameters'
            rgb_image:                        'carla/ego_vehicle/rgb_front/image'
            segmentation:                     'carla/ego_vehicle/semantic_segmentation_front/image'