lane_detection:
    ros__parameters:
        display:                              false
        frame_id:
            lane_parameters:                  'laneParametersFrameId'
        color:
            lane_marking:                     [157,234,50]
        m_per_pix:
            x:                                0.010278 # 3.7 meters / 360 pixels
            y:                                0.010417 # 5 meters / 480 pixels
        qos_length:                           10
        roi:
            height:                           151
            width1:                           151
            width2:                           405
            x1_offset:                        282
            x2_offset:                        156
            y_offset:                         329
        search_params:
            margin:                           50
            mean_limit:                       [4.5,8.5]
            min_pixels:                       40
            n_windows:                        10
        topic:
            lane_parameters:                  'carla_simulation/lane_parameters'
            rgb_image:                        'carla/ego_vehicle/rgb_front/image'
            segmentation:                     'carla/ego_vehicle/semantic_segmentation_front/image'
object_detection:
    ros__parameters:
        ## fov_per_pix:                          0.0032724923474893677 # (0.5 * pi) / 480
        frame_id:
            objects:                          'objectsFrameId'
        obj_class:
            name:                             ['person','vehicle']
            color:
                person:                       [220,20,60]
                vehicle:                      [0,0,142]
        qos_length:                           10
        topic:
            depth_image:                      'carla/ego_vehicle/depth_front/image'
            objects:                          'carla_simulation/objects'
            segmentation:                     'carla/ego_vehicle/semantic_segmentation_front/image'
