lane_detection:
    ros__parameters:
        frame_id:
            lane_parameters:                  'laneParametersFrameId'
        lane_color:                           [50,234,157]
        m_per_pix:
            x:                                0.010278 # 3.7 meters / 360 pixels
            y:                                0.033333 # 16 meters / 480 pixels
        qos_length:                           10
        roi:
            height:                           202
            width1:                           65
            width2:                           405
            x1_offset:                        327
            x2_offset:                        157
            y_offset:                         278
        search_params:
            margin:                           20
            mean_limit:                       10.0
            min_pixels:                       40
            n_windows:                        10
        topic:
            lane_parameters:                  'lane/parameters'
            rgb_image:                        'carla/ego_vehicle/rgb_front/image'
            segmentation:                     'carla/ego_vehicle/semantic_segmentation_front/image'